project:
  type: website
  output-dir: docs

website:
  title: "Sydney Beckett"
  navbar:
   right:
     - href: index.qmd
       text: Home
     - href: AboutMe.qmd
       text: About Me
     - href: ProjectPage.qmd
       text: Project Page
     - href: FreeForAll.qmd
       text: Passions
     - href: Resume.qmd
       text: Resume
     - href: posts.qmd
       text: Project Page
  page-footer:
     background: light
    

format:
  html:
    theme: journal
    mainfont: Noto Serif
    css: styles.scss
    toc: true
    page-layout: full

editor: visual

